### ISSUE TITLE
No module named 'ripplebehavior'

### ISSUE THREAD

**Issue by homdx** [Fox520/TinkleMessenger#1]
client run: `python main.py`

```
Traceback (most recent call last):
   File "main.py", line 53, in <module>
     from kivymd.bottomsheet import MDListBottomSheet
   File "TinkleMessenger/client/kivymd/bottomsheet.py", line 56, in <module>
     from kivymd.list import MDList, OneLineListItem, ILeftBody, \
   File "TinkleMessenger/client/kivymd/list.py", line 151, in <module>
     from ripplebehavior import RectangularRippleBehavior #
 ModuleNotFoundError: No module named 'ripplebehavior'
```

```
pip install ripplebehavior
Collecting ripplebehavior
  Could not find a version that satisfies the requirement ripplebehavior (from versions: )
No matching distribution found for ripplebehavior
You are using pip version 18.0, however version 19.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
```

**Comment by Fox520** [comment]
Facing trouble with reproducing the error. Both on Windows and Linux

What if you try this as a hack:

> `from . import ripplebehavior`
> `RectangularRippleBehavior = ripplebehavior.RectangularRippleBehavior`

**Comment by Fox520** [comment]
Issue is likely not present in latest version.
